### ISSUE TITLE
Application Error (The app stoped)

### ISSUE THREAD

**Issue by unf0rgvn** [Foo-Manroot/apk-patcher#1] opened 2024-09-14 22:08 UTC
Hi @Foo-Manroot , I tried to patch my APK file with `-f` option, but when I run the APK it crashes with the message`<apk_name> stoped.`. I tried to read the log while running the app and this is what is shown(I run the command: `adb logcat -v time .`, I don't if it's the right place to verify the thoug.):

```
09-14 18:54:29.811 E/AndroidRuntime(32009): Process: com.appname.123, PID: 32009
09-14 18:54:29.811 E/AndroidRuntime(32009): java.lang.VerifyError: Rejecting class com.appname.123.MainActivity because it failed compile-time verification (declaration of 'com.appname.123.MainActivity' appears in /data/app/com.appname.123-1/base.apk)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at java.lang.Class.newInstance(Native Method)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.Instrumentation.newActivity(Instrumentation.java:1096)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.ActivityThread.access$1100(ActivityThread.java:229)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.os.Handler.dispatchMessage(Handler.java:102)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.os.Looper.loop(Looper.java:148)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at android.app.ActivityThread.main(ActivityThread.java:7325)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at java.lang.reflect.Method.invoke(Native Method)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-14 18:54:29.811 E/AndroidRuntime(32009):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-14 18:54:29.811 W/ActivityManager(12584):   Force finishing activity com.appname.123/.MainActivity
09-14 18:54:29.821 D/InputDispatcher(12584): Focused application set to: xxxx
09-14 18:54:29.821 D/ActivityTrigger(12584): ActivityTrigger activityPauseTrigger
09-14 18:54:29.851 E/android.os.Debug(12584): ro.product_ship = true
09-14 18:54:29.851 E/android.os.Debug(12584): ro.debug_level = 0x4f4c
09-14 18:54:29.851 E/android.os.Debug(12584): sys.mobilecare.preload = false
09-14 18:54:29.851 I/SurfaceFlinger( 2331): id=430 Removed MauncherAct (2/10)
09-14 18:54:29.851 I/SurfaceFlinger( 2331): id=430 Removed MauncherAct (-2/10)
09-14 18:54:29.861 D/libEGL  ( 2331): eglTerminate EGLDisplay = 0xffd8ce64
09-14 18:54:29.861 D/ImageWallpaper( 8025): onVisibilityChanged:false
09-14 18:54:29.861 D/ImageWallpaper( 8025): drawFrame:falserotation:0mLastRotation:0
09-14 18:54:29.901 D/PackageManager(12584): [MSG] WRITE_PACKAGE_RESTRICTIONS
09-14 18:54:29.941 W/System.err(12584): remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
09-14 18:54:29.941 D/ViewRootImpl(12584): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{e0627d8 V.E...... R.....I. 0,0-0,0}
09-14 18:54:29.941 D/InputDispatcher(12584): Focus entered window: 12584
09-14 18:54:29.941 D/PointerIcon(12584): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:12584 uid:1000
09-14 18:54:29.941 D/PointerIcon(12584): setMouseCustomIcon IconType is same.101
09-14 18:54:29.941 V/MARsPolicyManager(12584): handelAlertToastWindowStarted pkgName = android
09-14 18:54:29.951 I/SurfaceFlinger( 2331): id=433 createSurf (97x97),1 flag=4, tcafit
09-14 18:54:29.971 D/libEGL  (12584): eglInitialize EGLDisplay = 0xd5f7d7c4
09-14 18:54:29.971 I/OpenGLRenderer(12584): Initialized EGL, version 1.4
09-14 18:54:29.971 I/BNRClientProivder, VERSION : 1.7.8(31982): register - xml6 quick_backup : WEATHERWIDGET, oo2JSUuSBb, com.sec.android.daemonapp.scloud.BNRTask
09-14 18:54:29.981 I/QBNRClientHelper(31982): init SyncClientHelper : WEATHERWIDGET
09-14 18:54:29.981 D/mali_winsys(12584): new_window_surface returns 0x3000,  [764x406]-format:1
09-14 18:54:29.981 D/StatusBarManagerService(12584): manageDisableList userId=0 what=0x0 pkg=Window{f0a5e16 u0 d0 p12584 Application Error: com.appname.123}
```

**Comment by Foo-Manroot** [comment] 2024-09-15 14:29
Hi

Thanks for the info!

I believe the issue is that my patching is a bit hacky: instead of using a [new register](https://github.com/JesusFreke/smali/wiki/Registers#how-method-parameters-are-passed-into-a-method), the script just assumes `v0` exists [and uses that](https://github.com/Foo-Manroot/apk-patcher/blob/ec76312e938beaba98b3e9d09d7df27977e0212f/Java/APK%20patcher/app/src/main/java/ApkPatcher/Patcher.java#L76).

However, some methods only receive parameters and have no local registers, so I'll have do it properly, I guess 😄 

I don't have much time right now; I may give it a shot next weekend.

In the meantime, I recommend you use the manual method (you can take inspiration from the [old-bash](https://github.com/Foo-Manroot/apk-patcher/blob/old-bash/split-apk-patcher.sh) branch). In rough terms:
  1. `baksmali d <your-base.apk>`
  2. modify `com.sistemasca.scafit.MainActivity`  to add `.locals 1` and the [gadget invokation](https://github.com/Foo-Manroot/apk-patcher/blob/4c108bd95f1de7f9cabe1554df854316b07e59e3/split-apk-patcher.sh#L262) stub
  3. assemble it back
  4. add the gadget to the libraries
  5. zip it and sign it alll

**Comment by Foo-Manroot** [comment] 2024-09-22 21:52
Hey, @unf0rgvn , the issue should be fixed now.
Please, try again with the new version and let me know if it doesn't work.

**Comment by unf0rgvn** [comment] 2024-09-24 00:16
Hey @Foo-Manroot, sorry for answering too late, I'll test it and if got any problema I'll let you know.  And another, where did you learn about those things? I mean, reverse engineering on android apps do you have any book/forum/youtube channel you can recommend me?

**Comment by unf0rgvn** [comment] 2024-09-24 21:03
I tried again with the new version but it shows up another problem. The app installation occurs with no errors but when I open it, the screen gets blank, as if it's loading the app, but never opens. Here is how I patched the app:

#### Process of getting the package:
```
1.  Download the app from PlayStore
2. Use: adb pull /data/app/com.appname.12345/  . --> copied every .apk from the path
```

### Process of patching
```
```

**Comment by unf0rgvn** [comment] 2024-09-24 21:14
I tried again with the new version but it shows up another problem. The app installation occurs with no errors but when I open it, the screen gets blank, as if it's loading the app, but never opens. Here is how I patched the app:

#### Process of getting the package:
```
1.  Download the app from PlayStore
2. Use: adb pull /data/app/com.appname.12345/  . --> copied every .apk from the path
```

### Process of patching
#### I created a directory and move all the .apk files to it, here is the apks file name:
**base.apk**, **split_config.armeabi_v7a.apk**, **split_config.es.apk**, **split_config.pt.apk**,  **split_config.xhdpi.apk**

```
1. I run this script to rename all apk's name: for i in $(ls .); do mv $i com.appname.1234.$i; done
Obs: The base.apk file I renamed to just: com.appname.1234.apk because it was giving me an error that the file was not found.

2. python3 apk-patcher.py -f dir/com.appname.1234.
3. Install the apk using adb;
4. Tries to open and it shows only a blank screen
```

**Comment by Foo-Manroot** [comment] 2024-09-25 08:04
I'm pretty sure that's the expected behaviour: when Frida loads, its default behaviour is to stop the execution and wait for an incoming connection from the Frida client. Can you check `adb logcat | grep -i frida` ?
Or, even simpler, you can just `frida -U Gadget` (assuming your device is connected via USB), and that should  resume the app execution.

Please, let me know if it works or if the bug persists.
<br/>

As for your previous question:
> where did you learn about those things?

Honestly, I just learnt by doing: reversing apps and creating tools like this one.
If you're asking a more general question about how to get started in mobile pentesting, take a look at the MASTG: https://mas.owasp.org/MASTG/

**Comment by unf0rgvn** [comment] 2024-09-26 00:30
I tried run this command(`frida -U Gadget`) now the app doesn't open and only shows "app_name stoped". I used logcat and it seems to be achitetures problems(I marked with '###'). The android device that I'm using now is armeabi-v7a.

```
09-25 21:20:02.801  2759  3720 D ActivityManager: isAutoRunBlockedApp:: com.appname.123, Auto Run ON
09-25 21:20:02.801  2759  3720 D ActivityManager: removeProcessNameLocked mProcessNames.remove pid=3485 ,hash=139422164 ,name=com.appname.123
09-25 21:20:02.801  2759  2972 V MARsPolicyManager: CurrentImportantPackage com.appname.123 -in latest protected packageslist for SPCM!
09-25 21:20:08.371  3559  3559 I Timeline: Timeline: Activity_launch_request id:com.appname.123 time:33502446
09-25 21:20:08.381  2759  2774 V WindowManager: addAppToken: AppWindowToken{2404e85 token=Token{c07b7fc ActivityRecord{e8390ef u0 com.appname.123/.MainActivity t16}}} to stack=1 task=16 at 0
09-25 21:20:08.431  2759  3006 V WindowStateAnimator: Finishing drawing window Window{f1657e8 u0 d0 p2759 Starting com.appname.123}: mDrawState=DRAW_PENDING
09-25 21:20:08.451  3602  3602 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.appname.123
09-25 21:20:08.461  2759  2775 I ActivityManager: Start proc 3602:com.appname.123/u0a185 for activity com.appname.123/.MainActivity
09-25 21:20:08.511  2759  3984 D ActivityManager:  Launching com.appname.123, updated priority
09-25 21:20:08.521  2759  2759 D GameManagerService: NotifyRunnable. pkg: com.appname.123, type: 4, isMinimized: false, isTunableApp: false
09-25 21:20:08.531  2759  2972 V MARsPolicyManager: updatePackagesScore PackageInfo name -- com.appname.123
09-25 21:20:08.531  2759  2974 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{f1657e8 u0 d0 p2759 Starting com.appname.123}
09-25 21:20:08.551  2759  7204 D GameManagerService: identifyGamePackage. com.appname.123
09-25 21:20:08.581  2759  3227 D PackageManager: setEnabledSetting : userId = 0 packageName = com.appname.123 cmp = androidx.work.impl.background.systemjob.SystemJobService newState = 1 callingPackage = 10185
09-25 21:20:08.811  3602  3602 E FlutterLoader: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E FlutterLoader: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E FlutterLoader: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appname.123-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.123-1/lib/arm, /data/app/com.appname.123-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
09-25 21:20:08.811  3602  3602 E AndroidRuntime: Process: com.appname.123, PID: 3602
### 09-25 21:20:08.811  3602  3602 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appname.123/com.appname.123.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not load libflutter.so this is possibly because the application is running on an architecture that Flutter Android does not support (e.g. x86) see https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures for more detail. ###
09-25 21:20:08.811  3602  3602 E AndroidRuntime: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E AndroidRuntime: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E AndroidRuntime: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E AndroidRuntime: App is using cpu architecture: armv8l, and the native libraries directory (with path /data/app/com.appname.123-1/lib/arm) contains the following files: [libgadget.so]
09-25 21:20:08.811  3602  3602 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appname.123-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sist
09-25 21:20:08.811  2759  3668 W ActivityManager:   Force finishing activity com.appname.123/.MainActivity
09-25 21:20:08.881  2759  2974 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{1397bad u0 d0 p2759 Application Error: com.appname.123}
09-25 21:20:08.901  2759  2974 V WindowStateAnimator: Finishing drawing window Window{1397bad u0 d0 p2759 Application Error: com.appname.123}: mDrawState=DRAW_PENDING
09-25 21:20:08.911  2759  2974 V WindowStateAnimator: Finishing drawing window Window{1397bad u0 d0 p2759 Application Error: com.appname.123}: mDrawState=HAS_DRAWN
09-25 21:20:09.331  2759  2972 W ActivityManager: Activity pause timeout for ActivityRecord{e8390ef u0 com.appname.123/.MainActivity t16 f}
09-25 21:20:09.391  2759  2974 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{1397bad u0 d0 p2759 Application Error: com.appname.123}
09-25 21:20:10.351  3389  3389 I ApplicationPackageManager: load=com.appname.123, bg=96-96, dr=96-96
09-25 21:20:12.621  2759  2775 I ActivityManager: Process com.appname.123 (pid 3602)(adj 9) has died(27,206)
09-25 21:20:12.621  2759  2775 D ActivityManager: isAutoRunBlockedApp:: com.appname.123, Auto Run ON
09-25 21:20:12.621  2759  2775 D ActivityManager: removeProcessNameLocked mProcessNames.remove pid=3602 ,hash=200084116 ,name=com.appname.123
```

**Comment by Foo-Manroot** [comment] 2024-09-26 09:03
Huh, that's interesring indeed

When I tried it with that app, it was working; but I downloaded it from apkpure or smth, where all architectures are packaged...

Can you please post the full output of `apk-patcher -vvvvvv dir/com.appname.1234.` ?

I also didn't use `-f` when I tried it, because it tends to break things; it's more a "last resource" kind of thing.

**Comment by unf0rgvn** [comment] 2024-09-26 14:35
Executed: `apk-patcher -vvvvvv dir/com.appname.1234.`
```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
2024-09-26 10:29:30.350 | INFO     | Set debugging level to TRACE
2024-09-26 10:29:30.350 | INFO     | Using /home/user/apk-patcher/appname/com.appname.1234.patched as working directory.
2024-09-26 10:29:30.351 | INFO     | Found parts: ['com.appname.1234.apk']
2024-09-26 10:29:30.387 | DEBUG    | Searching for the entry point using the following XPath: `.//activity/intent-filter/action[@{http://schemas.android.com/apk/res/android}name='android.intent.action.MAIN']/../..`
2024-09-26 10:29:30.387 | INFO     | Found entry point(s): ['com.appname.1234.MainActivity']
2024-09-26 10:29:30.467 | INFO     | Parsing classes.dex...
2024-09-26 10:29:32.358 | INFO     | Found init method: Lcom/appname/1234/MainActivity;-><init>()V [access_flags=public constructor] @ 0x1fe534
2024-09-26 10:29:32.359 | DEBUG    | Interfacing with the Java patcher to modify Lcom/appname/1234/MainActivity;-><init>// Dex version: 35
[INFO][JAVA] Parsing DEX file Lcom/appname/1234/MainActivity;-><init>
[DEBUG][JAVA] Size of the original DEX: 4568136 Bytes
[DEBUG][JAVA] Size of the new generated DEX: 4582724 Bytes
2024-09-26 10:29:35.164 | DEBUG    | Deducted ABI from file /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.apk: appname
2024-09-26 10:29:35.164 | DEBUG    | Failed to find appname within the ABI_MAPPING: {'armeabi-v7a': 'arm', 'arm64-v8a': 'arm64', 'x86': 'x86', 'x86_64': 'x86_64'}
2024-09-26 10:29:35.164 | INFO     | Requesting https://api.github.com/repos/frida/frida/releases/latest
2024-09-26 10:29:35.826 | INFO     | Using Frida version 16.5.2 (latest)
2024-09-26 10:29:36.027 | INFO     | Processing architecture arm
2024-09-26 10:29:36.027 | INFO     | Located frida-gadget-16.5.2-android-arm.so.xz @ https://github.com/frida/frida/releases/download/16.5.2/frida-gadget-16.5.2-android-arm.so.xz
2024-09-26 10:29:40.129 | DEBUG    | Added all *.so to /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.tmp!lib/armeabi-v7a/
2024-09-26 10:29:40.129 | INFO     | Processing architecture arm64
2024-09-26 10:29:40.129 | INFO     | Located frida-gadget-16.5.2-android-arm64.so.xz @ https://github.com/frida/frida/releases/download/16.5.2/frida-gadget-16.5.2-android-arm64.so.xz
2024-09-26 10:29:42.141 | DEBUG    | Added all *.so to /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.tmp!lib/arm64-v8a/
2024-09-26 10:29:42.142 | INFO     | Processing architecture x86
2024-09-26 10:29:42.142 | INFO     | Located frida-gadget-16.5.2-android-x86.so.xz @ https://github.com/frida/frida/releases/download/16.5.2/frida-gadget-16.5.2-android-x86.so.xz
2024-09-26 10:29:44.430 | DEBUG    | Added all *.so to /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.tmp!lib/x86/
2024-09-26 10:29:44.431 | INFO     | Processing architecture x86_64
2024-09-26 10:29:44.431 | INFO     | Located frida-gadget-16.5.2-android-x86_64.so.xz @ https://github.com/frida/frida/releases/download/16.5.2/frida-gadget-16.5.2-android-x86_64.so.xz
2024-09-26 10:29:46.783 | DEBUG    | Added all *.so to /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.tmp!lib/x86_64/
2024-09-26 10:29:46.841 | DEBUG    | Processing /home/user/apk-patcher/appname/com.appname.1234.patched/com.appname.1234.apk
2024-09-26 10:29:46.841 | DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 111564420 Bytes // Aligned Zip file: 111574442 Bytes.
2024-09-26 10:29:47.555 | DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
2024-09-26 10:29:48.582 | SUCCESS  | [+] All done! The output APK can be found under /home/user/apk-patcher/appname/com.appname.1234.patched
```

**Comment by Foo-Manroot** [comment] 2024-09-26 17:35
Ok, I see

So, according to my understanding (from https://developer.android.com/ndk/guides/abis.html#native-code-in-app-packages and from the apps I've seen), native libraries are placed inside one of the following directories:
  - lib/armeabi-v7a/
  - lib/arm64-v8a/
  - lib/x86/
  - lib/x86_64/

Since the app you're trying to patch is not split (i.e.: there's only `base.apk`), my script cannot infer the required architecture so it downloads all versions of Frida and places them inside the final, patched APK.

However, for some reason, it looks like the app you're trying to patch has its native libraries placed inside `lib/arm`, instead of the ones stated in the Android documentation.

Could you please give me the following info:
  - In the original APK: what is under `lib/` (you can decompress the apk by simply unzipping it)
  - In the patched APK: what is under `lib/`
  - On your device, with the app installed: what is under `/data/app/<the-app-name>/lib/`

Worst case, I can just add a new flag to my script to specify the architecture and the target directory (which is probably a good idea anyways :smile: )

If you want, you can also just upload your target apk here and I will take a look by myself.

**Comment by unf0rgvn** [comment] 2024-09-26 18:35
Yeah, I think it's best to share the app with you😄. I download from Apkpure. Do you want to me to verify the infos or you will test it?
Github doesn't permit to upload .xapk or .apk files I uploaded on this site: https://www.transfernow.net/dl/20240926uPTSpN96

**Comment by Foo-Manroot** [comment] 2024-09-26 21:32
Well, that's exactly the same app I tried it the first time, so something else is going on.

The exact process to patch this APK is:
1. `7z x ../SCA\ Fit_1.5.0_APKPure.xapk`
2. `$ rename -v config. com.sistemasca.scafit.config. config.*` :
```
`config.armeabi_v7a.apk' -> `com.sistemasca.scafit.config.armeabi_v7a.apk'
`config.en.apk' -> `com.sistemasca.scafit.config.en.apk'
`config.fr.apk' -> `com.sistemasca.scafit.config.fr.apk'
`config.mdpi.apk' -> `com.sistemasca.scafit.config.mdpi.apk'
```
3. `$ apk-patcher -vv com.sistemasca.scafit.` (note the dot at the end):
```
| INFO     | Set debugging level to DEBUG
| INFO     | Using Downloads/com.sistemasca.scafit.patched as working directory.
| INFO     | Found parts: ['com.sistemasca.scafit.apk', 'com.sistemasca.scafit.config.armeabi_v7a.apk', 'com.sistemasca.scafit.config.mdpi.apk', 'com.sistemasca.scafit.config.en.apk', 'com.sistemasca.scafit.config.fr.apk']
[...]
| DEBUG    | Inferred ABI from file com.sistemasca.scafit.config.armeabi_v7a.apk: armeabi_v7a
| INFO     | Requesting https://api.github.com/repos/frida/frida/releases/latest
| INFO     | Using Frida version 16.5.2 (latest)
| INFO     | Processing architecture arm
| INFO     | Located frida-gadget-16.5.2-android-arm.so.xz @ https://github.com/frida/frida/releases/download/16.5.2/frida-gadget-16.5.2-android-arm.so.xz
| DEBUG    | Added all *.so to Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.config.armeabi_v7a.apk!lib/armeabi-v7a/
| DEBUG    | Processing Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.apk
| DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 7821230 Bytes // Aligned Zip file: 7821569 Bytes.
| DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
| DEBUG    | Processing Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.config.armeabi_v7a.apk
| DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 38735684 Bytes // Aligned Zip file: 38746713 Bytes.
| DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
| DEBUG    | Processing Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.config.mdpi.apk
| DEBUG    | Copying unmodified file: com.sistemasca.scafit.config.mdpi.apk
| DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 55207 Bytes // Aligned Zip file: 55207 Bytes.
| DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
| DEBUG    | Processing Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.config.en.apk
| DEBUG    | Copying unmodified file: com.sistemasca.scafit.config.en.apk
| DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 41369 Bytes // Aligned Zip file: 41369 Bytes.
| DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
| DEBUG    | Processing Downloads/com.sistemasca.scafit.patched/com.sistemasca.scafit.config.fr.apk
| DEBUG    | Copying unmodified file: com.sistemasca.scafit.config.fr.apk
| DEBUG    | Zipaligning...
[DEBUG][JAVA] Original Zip file: 24985 Bytes // Aligned Zip file: 24985 Bytes.
| DEBUG    | Signing...
[DEBUG][JAVA] Apk signed.
| SUCCESS  | [+] All done! The output APK can be found under Downloads/com.sistemasca.scafit.patched
```
3. `$ adb install-multiple com.sistemasca.scafit.apk com.sistemasca.scafit.config.armeabi_v7a.apk com.sistemasca.scafit.config.en.apk com.sistemasca.scafit.config.mdpi.apk`

If I understood the information you gave me correctly, this is indeed a split APK, so you must give a common base name to all files (note the step 2 above) for the script to pick them up.

Those are the steps I followed to get my patched APK running on my device.

Does this solve your issue?

**Comment by unf0rgvn** [comment] 2024-09-26 23:49
Now it works!! With and without the `-f` option. Thank you so much for the help!🥳🥳🥳

**Closed as completed** 2024-09-28 12:59 UTC
